### ISSUE TITLE
Error in extracting CTF file

### ISSUE THREAD

**Issue by Giacomoalciatore** [Social-Evolution-and-Behavior/anTraX#11]
Hello,
I'm running antrax on two different HPC environments and suddenly one of them stopped working properly, while the other one still works fine. I tried both "master" and "debug-giacomo" branches.
When I run the function solve, I get the following message in both the matlab_solve.log and matlab_export.log files:

```
Error in extracting CTF file to '/users/tkay/.mcrCache9.6/antrax1'. Details: 'Could not create file: /users/tkay/.mcrCache9.6/antrax1/toolbox/shared/spcuilib/unifiedscopes/@uiservices/@DialogBase/closedlg.m'
Could not access the MATLAB Runtime component cache. Details: Some error has occurred in the file: core/mclCtfFileExtractor.cpp, at line: 64.
 The error message is: 
Error in extracting CTF file to '/users/tkay/.mcrCache9.6/antrax1'. Details: 'Could not create file: /users/tkay/.mcrCache9.6/antrax1/toolbox/shared/spcuilib/unifiedscopes/@uiservices/@DialogBase/closedlg.m'
; component cache root:/users/tkay/.mcrCache9.6; componentname: antrax_glnxa64_mcr_interface
```

I haven't changed the runtime version that was working before, nor the path to the matlab version, any idea what might cause this problem?

**Comment by asafgal** [comment]
MATLAB creates a cache directory during mcr execution. Somehow it cannot write to this directory.

First, make sure it is a not a trivial problem like a full disk or write permissions. If all is good, try deleting the cache directory (/users/tkay/.mcrCache9.6/antrax1 in your case).

**Comment by Giacomoalciatore** [comment]
It was indeed an issue with writing permission, thanks
