### ISSUE TITLE
MATLAB:badsubscript error crashes solve step 

### ISSUE THREAD

**Issue by Giacomoalciatore** [Social-Evolution-and-Behavior/anTraX#22]
An Error similar to https://github.com/Social-Evolution-and-Behavior/anTraX/issues/17#issue-838627959 but happens during the solving step, and it causes the job to crash and no output to be exported. The full error message is:
```

10:49:18 -I- Reading video information from file
10:49:53 -I- Loading trgraph from antrax/graphs/C6/graph_9_9.mat
10:50:09 -I- Finished loading trgraph with 2025 tracklets
10:50:09 -I- Loading ids
10:50:11 -I- Finding single ant nodes
10:50:11 -I- Some preperations
10:50:12 -I- Looking for bottleneck pairs
10:50:12 -I- done distance mat
Index in position 2 exceeds array bounds.
Error in trgraph/get_bottleneck_pairs (line 523)

Error in trgraph/solve (line 28)

Error in solve_single_movie (line 54)

Error in antrax_mcr_interface (line 30)
MATLAB:badsubscript
```

Thanks!

**Comment by janamach** [comment]
Hi,

I was having similar errors in #20 (the issue was poorly named, I just renamed it). In case you don't hear from Asaf soon, try switching to `debug-jana` branch and see if that helps.

**Comment by asafgal** [comment]
Hey Giacomo, Jana is right, this issue will probably be resolved by the patch I provided her. I have now merged this fix into the master branch and the debug-giacomo branch. Let me know if it works!
