### ISSUE TITLE
MCR Interface scaling on high resolution displays

### ISSUE THREAD

**Issue by janamach** [Social-Evolution-and-Behavior/anTraX#24]
Hi!

Not sure if this is an anTraX problem per se, but the menu text is awfully small on a 4K display. MATLAB full installation seems to have a solution for this (e.g., [here](https://www.mathworks.com/matlabcentral/answers/406956-does-matlab-support-high-dpi-screens-on-linux)), but I didn't find anything for MCR.

With MCR it looks like this on 4K:
![Screenshot from 2021-06-04 09-26-54](https://user-images.githubusercontent.com/39128466/120763621-b108dd80-c517-11eb-964c-18cb29e0d7e3.png)
The text on the left is "normal"  size. MCR seems to ignore the system-wide scaling settings. Do you happen to have a quick solution for this?

**Comment by asafgal** [comment]
Hmmm... I don't have any experience with this. Maybe the setting change need to be done inside the compiled program. I'll give it a try next time I compile...

**Comment by janamach** [comment]
My apologies, looks like the bug is in nvidia driver and not in your software. This problem extends to some other GUIs, including inkscape stable and arduino. Purging all nvidia software "solved" the problem.

**Comment by janamach** [comment]
Hi again. This "bug" got magically fixed when I switched from using HDMI to DisplayPort cable. Very strange. Feel free to close this issue.

**Comment by asafgal** [comment]
Thanks Jana, glad you figured it out
