### ISSUE TITLE
Many small non-ant objects still tracked and classified

### ISSUE THREAD

**Issue by Giacomoalciatore** [Social-Evolution-and-Behavior/anTraX#27]
Hi,
I have many videos in which small particles of food or trashed are tracked, increasing enormously the size of the trajectories tracked (15000+ for 10 minutes videos), and slowing down the classification and trainset-extraction steps. These objects are smaller than the min area single ant threshold, and are marked with a pink outline. Would it be possible to include an option that tells the software to discard automatically all pink blobs below the min area threshold?

**Comment by asafgal** [comment]
Hey Giacomo, use the "min area" parameter in the segmentation tab to set a threshold under which blobs are discarded.

**Comment by Giacomoalciatore** [comment]
Thanks!
