### ISSUE TITLE
Problems with compiling mex file

### ISSUE THREAD

**Issue by Sean-Nolan6** [Social-Evolution-and-Behavior/anTraX#33]
Hi I'm trying to install the software for a project and ran into this issue when compiling the mex file.
I am not a coding person so have no idea what any of this means, but would appreciate any help!

sean@sean-VirtualBox:~/Downloads/anTraX/matlab/external/popenmatlab$ mex popenr.c
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=mex)
 restricted \write18 enabled.
entering extended mode
(./popenr.c
This is MeX  Version 1.05  18 XII 1993  (B. Jackowski & M. Ry\'cko)

Overfull \hbox (166.50084pt too wide) in paragraph at lines 1--14
\tenrm EOF, re-turn ma-trix si-zed ac-cor-ding to what was ac-tu-ally read * * 
$\teni Header \tenrm : \teni =homes=drspeech=src=matlabpopen=RCS=popenr:c; v\te
nrm 1\teni :\tenrm 22007\teni =\tenrm 01\teni =\tenrm 1404 :|
! You can't use `macro parameter character #' in vertical mode.
l.15 #
      include    <stdio.h>
? ^C! Interruption.
<to be read again> 
                   i
l.15 #i
       nclude    <stdio.h>
?

**Comment by asafgal** [comment]
Hey Sean, note that the mex command is a matlab command that should be run from within the matlab command line. If you don’t have matlab and plan to use mcr, there is no need to run it!
