### ISSUE TITLE
solve step 1 produce error contains `MATLAB:UndefinedFunction`

### ISSUE THREAD

**Issue by lizimai** [Social-Evolution-and-Behavior/anTraX#37]
Hi :) I am running the solve step 1 on a SLURM cluster with command `antrax solve EXPDIR --step 1 --clist 1 --hpc --hpc-options cpus=3,mem-per-cpu=3000,time=72:00:00`, and encountered two types of error in some of the `.log` files (see below). I have 334 videos, each includes 6 colonies, and 211 of them has at least 1 colony failed in the solve step 1. logs of `track` step does not show error. 
```
$ cat matlab_solve_m_263_c_1.log
02:57:52 -I- Reading video information from file
02:58:02 -I- Loading trgraph from antrax_20220112/graphs/C1/graph_263_263.mat
02:58:03 -I- Finished loading trgraph with 10 tracklets
02:58:04 -I- Loading ids
02:58:04 -I- Finding single ant nodes
02:58:04 -I- Some preperations
02:58:04 -I- Looking for bottleneck pairs
02:58:04 -I- done distance mat
Undefined function or variable 'pairs'.
Error in trgraph/get_bottleneck_pairs (line 515)

Error in trgraph/solve (line 28)

Error in solve_single_movie (line 54)

Error in antrax_mcr_interface (line 30)
MATLAB:UndefinedFunction

$ cat matlab_solve_m_303_c_1.log
03:01:16 -I- Reading video information from file
03:01:28 -I- Loading trgraph from antrax_20220112/graphs/C1/graph_303_303.mat
Warning: Variable 'trjs' not found.
> In trgraph.load (line 875)
  In trhandles/loaddata (line 609)
  In solve_single_movie (line 52)
  In antrax_mcr_interface (line 30)
Undefined function or variable 'trjs'.
Error in trgraph.load (line 876)

Error in trhandles/loaddata (line 609)

Error in solve_single_movie (line 52)

Error in antrax_mcr_interface (line 30)
MATLAB:UndefinedFunction
```

**Comment by asafgal** [comment]
So I get it that the track step for these videos finished successfully? It looks like a problem with degenerated graphs that have none or very few tracklets. It's similar one of the issues we debugged with Jana a while ago. I’ll try looking into it later today.

**Comment by lizimai** [comment]
The track log does not have error. I just had a look at the graph files, seems the `graph_263_263_trjs.mat` and `graph_303_303_trjs.mat` cannot be opened by Matlab. And inside `graph_263_263.mat` the index of tracklets are `NaN`.

**Comment by lizimai** [comment]
I just got an update from the IT department. The anTraX that is installed on our server is from Feb 2021 (I assumed it to be the latest version since the version number is also v1.0.2). Most likely my error is the same as Jana's and the update on fixing Jana's bug is not included. I have asked them to update anTrax and will rerun the track and solve. Sorry for taking your time!  If the issue is solved after update, I will close the issue.

**Comment by janamach** [comment]
@lizimai Why are you asking the IT to do this for you?
